apiVersion: v1
kind: Pod
metadata:
  name: on-failure2
  labels:
    app: app1
spec:
  containers:
  - name: never
    image: busybox # Imagen 
    # Ejecutamos un comando. Saca en pantalla un mensaje y se sale.
    command: ['sh', '-c', 'echo Ejemplo de pod fallado  && exit 1']
  restartPolicy: OnFailure