apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
     app: nginx 
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002 # Aquí especificamos el puerto
    protocol: TCP
  selector:
     app: nginx #Es el que relaciona los contenedores y los pods y los despliegues
